defaults:
  - _self_
  - model: linear_regression

train_features: data/processed/green_tripdata_2021-01_features.csv
train_target: data/processed/green_tripdata_2021-01_target.csv
valid_features: data/processed/green_tripdata_2021-02_features.csv
valid_target: data/processed/green_tripdata_2021-02_target.csv

log_all_model_params: false
